In [1]:
import pandas as pd
import numpy as np

import glob
from ase.io import read
from dscribe.descriptors import ACSF

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
import pylab as pl


import random
import sys

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics

from pandas import set_option
pd.options.mode.chained_assignment = None

from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from scipy.stats import truncnorm
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [19]:
name = 'apoCaM-CA-Ng.loop3.water4.frame40'
pdb_file = name+'.pdb'
chg_file = name + '.chg'
structure = read("pdb/"+pdb_file)
feat_lst=[]
num=structure.get_global_number_of_atoms()
atomPos = [x for x in range(0,num)]

chg=np.genfromtxt("charge/"+chg_file)


# Setting up the ACSF descriptor
for r_cut in [6.0]:
    acsf = ACSF(
        species=["C", "H", "O", "N", "Ca"],
        rcut=r_cut,
        g2_params=[[0.0001,0]],
    )

onlyg2 = acsf.create(structure,positions=atomPos,n_jobs=4)

acsf_ang = ACSF(
    species=["C", "H", "O", "N", "Ca"],
    rcut=6.0,
    g4_params=[[0.0001,0.5,-1]],
)

onlyg4 = acsf_ang.create(structure,positions=atomPos,n_jobs=4)


In [20]:
onlyg2

array([[4.6984415 , 4.6953154 , 1.8370903 , ..., 1.0722741 , 0.        ,
        0.        ],
       [5.9964924 , 5.9913335 , 3.4576583 , ..., 1.8980758 , 0.        ,
        0.        ],
       [6.086594  , 6.080134  , 4.908716  , ..., 1.2281281 , 0.        ,
        0.        ],
       ...,
       [3.5650806 , 3.5627358 , 0.5433005 , ..., 2.4018583 , 0.58264303,
        0.5822238 ],
       [2.0980828 , 2.0958838 , 0.5421028 , ..., 2.7594974 , 0.4422125 ,
        0.44175386],
       [2.1727443 , 2.170898  , 0.25211582, ..., 2.51684   , 0.37936074,
        0.37890542]], dtype=float32)

In [21]:
onlyg4

array([[4.6984415 , 1.8370903 , 0.87384135, ..., 0.        , 0.        ,
        0.        ],
       [5.9964924 , 3.4576583 , 1.5705079 , ..., 0.        , 0.        ,
        0.        ],
       [6.086594  , 4.908716  , 1.7775744 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [3.5650806 , 0.5433005 , 0.        , ..., 0.        , 0.69083273,
        0.        ],
       [2.0980828 , 0.5421028 , 0.        , ..., 0.        , 0.561925  ,
        0.        ],
       [2.1727443 , 0.25211582, 0.        , ..., 0.        , 0.3663049 ,
        0.        ]], dtype=float32)

In [23]:
onlyg4[:,2:]

array([[0.87384135, 1.0735173 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.5705079 , 1.8999021 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.7775744 , 1.2301179 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 2.404673  , 0.58264303, ..., 0.        , 0.69083273,
        0.        ],
       [0.        , 2.761958  , 0.4422125 , ..., 0.        , 0.561925  ,
        0.        ],
       [0.        , 2.5191047 , 0.37936074, ..., 0.        , 0.3663049 ,
        0.        ]], dtype=float32)

In [24]:
from dscribe.descriptors import ACSF

# Setting up the ACSF descriptor
acsf = ACSF(
    species=["H", "O"],
    rcut=6.0,
    #g2_params=[[1, 1], [1, 2], [1, 3]],
    g4_params=[[1, 1, 1], [1, 2, 1], [1, 1, -1], [1, 2, -1]],
)

from ase.build import molecule

water = molecule("H2O")

# Create MBTR output for the hydrogen atom at index 1
acsf_water = acsf.create(water, positions=[1])

print(acsf_water)
print(acsf_water.shape)

[[8.4861797e-01 9.3706870e-01 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 1.9852765e-02 1.7748473e-02 2.3537816e-03 2.4948895e-04
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
(1, 14)


In [ ]:
[[0.848618   0.9370687  0.         0.01985276 0.        ]]
