In [1]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))
StandardScaler()
print(scaler.mean_)
print(scaler.transform(data))
print(scaler.transform([[2, 2]]))

StandardScaler(copy=True, with_mean=True, with_std=True)
[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[3. 3.]]


In [3]:
scaler.mean_

array([0.5, 0.5])

In [7]:
scaler.var_

array([0.25, 0.25])

In [1]:
from Bio.PDB import *
from biopandas.mol2 import PandasMol2
import glob
import math
import numpy as np
import sys

In [2]:
snapshot = "pdb/holoCaM.loop3.water3.frame117.mol2"

In [3]:
pmol = PandasMol2().read_mol2(snapshot)

In [11]:
pmol.df.size

1638

In [12]:
len(pmol.df)

182

In [26]:
pmol.df[pmol.df.atom_type == 'hc']

atom_id atom_name       x      y      z atom_type  subst_id subst_name  \
3          4        H1   2.227 -5.873  6.234        hc         1        MOL   
4          5        H2   1.822 -4.262  6.871        hc         1        MOL   
5          6        H3   0.530 -5.445  6.556        hc         1        MOL   
16        17        H6   3.999 -2.114  3.520        hc         1        MOL   
17        18        H7   2.631 -1.018  3.714        hc         1        MOL   
29        30       H10   0.057 -6.790  1.016        hc         1        MOL   
30        31       H11   0.583 -7.494 -0.508        hc         1        MOL   
31        32       H12   0.171 -5.257 -1.655        hc         1        MOL   
32        33       H13  -0.427 -4.701 -0.121        hc         1        MOL   
33        34       H14  -2.061 -6.577 -0.136        hc         1        MOL   
34        35       H15  -1.443 -7.203 -1.594        hc         1        MOL   
50        51       H23   2.927 -4.624 -3.534        hc         1        MOL   
51        52       H24   4.291 -3.692 -3.979        hc         1        MOL   
69        70       H30   5.302  1.319 -3.525        hc         1        MOL   
70        71       H31   5.498  2.960 -2.849        hc         1        MOL   
94        95       H39   0.756  5.006 -0.086        hc         1        MOL   
95        96       H40   1.907  4.004 -0.812        hc         1        MOL   
111      112       H48  -2.849  0.681  2.175        hc         1        MOL   
112      113       H49  -3.559  2.723  3.234        hc         1        MOL   
113      114       H50  -1.912  3.104  3.752        hc         1        MOL   
114      115       H51  -0.605  0.822  3.961        hc         1        MOL   
115      116       H52  -1.307 -0.608  3.028        hc         1        MOL   
116      117       H53  -0.107  0.363  2.329        hc         1        MOL   
117      118       H54  -2.070  1.652  5.594        hc         1        MOL   
118      119       H55  -3.508  2.483  5.399        hc         1        MOL   
119      120       H56  -3.417  0.741  4.907        hc         1        MOL   
138      139       H64  -9.346  4.253 -1.031        hc         1        MOL   
139      140       H65 -10.291  3.453  0.383        hc         1        MOL   
140      141       H66  -9.010  4.604  0.711        hc         1        MOL   
148      149       H69  -7.298  0.077 -3.615        hc         1        MOL   
149      150       H70  -8.374 -1.316 -3.871        hc         1        MOL   
150      151       H71  -8.958  0.326 -3.847        hc         1        MOL   
162      163       H74  -3.189 -1.503  0.533        hc         1        MOL   
163      164       H75  -3.981 -0.090  0.074        hc         1        MOL   
164      165       H76  -4.263 -1.060 -2.294        hc         1        MOL   
165      166       H77  -3.270 -2.336 -1.827        hc         1        MOL   

       charge  
3    0.122973  
4    0.122973  
5    0.122973  
16   0.019735  
17   0.019735  
29   0.054099  
30   0.054099  
31  -0.011155  
32  -0.011155  
33   0.013027  
34   0.013027  
50   0.075399  
51   0.075399  
69   0.131750  
70   0.131750  
94  -0.113756  
95  -0.113756  
111 -0.039702  
112  0.053955  
113  0.053955  
114  0.075525  
115  0.075525  
116  0.075525  
117  0.094135  
118  0.094135  
119  0.094135  
138  0.166879  
139  0.166879  
140  0.166879  
148  0.047949  
149  0.047949  
150  0.047949  
162 -0.027121  
163 -0.027121  
164  0.039902  
165  0.039902

In [34]:
from ase.io import mol

In [28]:
structure = read(snapshot)

UnknownFileTypeError: mol2

In [36]:
structure =mol.read_mol(snapshot)

AttributeError: 'str' object has no attribute 'readlines'

In [37]:
help(mol.read_mol)

Help on function read_mol in module ase.io.mol:

read_mol(fileobj)

